Logistic classification

In [0]:
import tensorflow as tf

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0],[0],[0],[1],[1],[1]]
x = tf.placeholder(tf.float32, shape=[None,2])
y = tf.placeholder(tf.float32, shape=[None,1])
w = tf.Variable(tf.random_normal([2,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.sigmoid(tf.matmul(x,w) + b)

cost = -tf.reduce_mean(y * tf.log(hypothesis) + (1-y)*tf.log(1-hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, y), dtype=tf.float32))

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

  for step in range(10001):
    cost_val, _ = sess.run([cost, train], feed_dict = {x: x_data, y: y_data})
    if step % 200 == 0:
      print(step, cost_val)

  h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={x: x_data, y:y_data})
  print("\nHypothesis: ", h, "\nCorrect(Y): ", c, "\nAccuracy: ", a)

Multinomial Logistic Regression

In [0]:
import tensorflow as tf

x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

x = tf.placeholder("float", [None,4])
y = tf.placeholder("float", [None,3])
nb_classes = 3

w = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(x,w) + b)

cost = tf.reduce_mean(-tf.reduce_sum(y* tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

  for step in range(2001):
    sess.run(optimizer, feed_dict = {x:x_data, y:y_data})
    if step % 200 == 0:
      print(step, sess.run(cost, feed_dict={x:x_data, y:y_data}))
  
  a=sess.run(hypothesis, feed_dict={x:[[1,11,7,9]]})
  print(a, sess.run(tf.arg_max(a,1)))

  a11=sess.run(hypothesis, feed_dict={x:[[1,11,7,9], [1,3,4,3],[1,1,0,1]]})
  print(a11, sess.run(tf.arg_max(a11,1)))

0 2.5317116
200 0.5536535
400 0.45156804
600 0.35848534
800 0.27179432
1000 0.23494332
1200 0.21317217
1400 0.19500089
1600 0.17959142
1800 0.16636056
2000 0.15488136
[[1.8113563e-02 9.8187929e-01 7.1639020e-06]] [1]
[[1.8113563e-02 9.8187929e-01 7.1639024e-06]
 [7.3592943e-01 2.4627391e-01 1.7796690e-02]
 [7.8037914e-09 3.0394897e-04 9.9969602e-01]] [1 0 2]
